In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

In [2]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [3]:
df.shape

(1000, 12)

In [4]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Total_Sales'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [6]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [7]:
df.fillna(method='ffill', inplace=True)

/tmp/ipykernel_2964/3970806690.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [10]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df = df.drop_duplicates()

In [14]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [15]:
df.dtypes

Order_ID                 object
Order_Date       datetime64[ns]
Customer_ID              object
Customer_Name            object
Age                     float64
Gender                   object
City                     object
Product                  object
Category                 object
Quantity                  int64
Unit_Price              float64
Total_Sales             float64
dtype: object

In [16]:
df["City"] = df["City"].str.title()

In [17]:
df["Product"] = df["Product"].str.title()

In [18]:
df["Category"] = df["Category"].str.title()

In [19]:
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["Age"] < lower) | (df["Age"] > upper)]

In [20]:
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["Age"] < lower) | (df["Age"] > upper)]

In [21]:
df["Order_Year"] = df["Order_Date"].dt.year

In [22]:
df["Order_Month"] = df["Order_Date"].dt.month_name()

In [23]:
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0,25,40,60,100],
    labels=["Young","Adult","Middle Age","Senior"]
)

In [24]:
df["Revenue_Per_Unit"] = (
    df["Total_Sales"] / df["Quantity"]
)

In [25]:
df.to_csv(
    "cleaned_apexplanet_dataset.csv",
    index=False
)

In [26]:
import pandas as pd

data_dictionary = pd.DataFrame({
    "Column Name": [
        "Order_ID",
        "Order_Date",
        "Customer_ID",
        "Customer_Name",
        "Age",
        "Gender",
        "City",
        "Product",
        "Category",
        "Quantity",
        "Unit_Price",
        "Total_Sales",
        "Order_Year",
        "Order_Month",
        "Age_Group",
        "Revenue_Per_Unit"
    ],

    "Data Type": [
        "Text",
        "Date",
        "Text",
        "Text",
        "Integer",
        "Text",
        "Text",
        "Text",
        "Text",
        "Integer",
        "Float",
        "Float",
        "Integer",
        "Text",
        "Text",
        "Float"
    ],

    "Description": [
        "Unique order identifier",
        "Date when the order was placed",
        "Unique customer identifier",
        "Name of the customer",
        "Customer age",
        "Customer gender",
        "Customer city",
        "Product purchased",
        "Product category",
        "Number of units purchased",
        "Price per unit",
        "Total revenue generated from the order",
        "Year extracted from Order Date",
        "Month extracted from Order Date",
        "Customer age category",
        "Revenue generated per unit sold"
    ]
})

data_dictionary

         Column Name Data Type                             Description
0           Order_ID      Text                 Unique order identifier
1         Order_Date      Date          Date when the order was placed
2        Customer_ID      Text              Unique customer identifier
3      Customer_Name      Text                    Name of the customer
4                Age   Integer                            Customer age
5             Gender      Text                         Customer gender
6               City      Text                           Customer city
7            Product      Text                       Product purchased
8           Category      Text                        Product category
9           Quantity   Integer               Number of units purchased
10        Unit_Price     Float                          Price per unit
11       Total_Sales     Float  Total revenue generated from the order
12        Order_Year   Integer          Year extracted from Order Date
13       Order_Month      Text         Month extracted from Order Date
14         Age_Group      Text                   Customer age category
15  Revenue_Per_Unit     Float         Revenue generated per unit sold

In [27]:
data_dictionary.to_excel(
    "data_dictionary.xlsx",
    index=False
)

print("Data Dictionary Created Successfully!")

Data Dictionary Created Successfully!